routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::prefix('sites')->group(function () {

    Route::get('/', 'UserSitesController@index')->name('mySites');
    Route::get('create', 'UserSitesController@create')->name('create');
    Route::post('save', 'UserSitesController@save')->name('save');
    Route::get('edit/{id}', 'UserSitesController@edit')->name('edit');
    Route::get('delete/{id}', 'UserSitesController@delete')->name('delete');
    Route::get('update/{id}', 'UserSitesController@update')->name('update');
    Route::get('change_default/{id}', 'UserSitesController@change_default')->name('change_default');

});

Route::prefix('scripts')->group(function (){

    Route::get('set_script/{id}', 'Scripts\ScriptController@set_script')->name('set_script');
    Route::any('/generate_script', 'Scripts\ScriptController@generate_script');

});



//Bars Crud
Route::resource('bars', 'Bars\BarController');

//FacebookBar Crud
Route::resource('facebook', 'Bars\FacebookBarController');


//QuizBar Crud
Route::resource('quiz_bar', 'Bars\QuizController');

Route::prefix('facebook')->group(function (){

    Route::get('ajax_delete_page/{id}', 'Bars\FacebookBarController@ajax_delete_page')->name('ajax_delete_page');

});

//errors
Route::prefix('error')->group(function (){
    Route::get('not-valid', 'ErrorController@notValid')->name('not-valid');
});

//google login

Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('login/google');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

//verify email
Route::get('verifyEmailFirst', 'Auth\RegisterController@verifyEmailFirst')->name('verifyEmailFirst');
Route::get('verify/{verifyToken}', 'Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

resources/views/includes/_footer.blade.php
<!-- jQuery -->
<script src="{{asset('tamplate/vendor/jquery/jquery.min.js')}}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{asset('tamplate/vendor/bootstrap/js/bootstrap.min.js')}}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{{asset('tamplate/vendor/metisMenu/metisMenu.min.js')}}"></script>

<!-- Morris Charts JavaScript -->
<script src="{{asset('tamplate/vendor/raphael/raphael.min.js')}}"></script>

<!-- Custom Theme JavaScript -->
<script src="{{asset('tamplate/dist/js/sb-admin-2.js')}}"></script>

{{--Main Js--}}
<script src="{{asset('js/main.js')}}"></script>

resources/views/includes/_header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CoolBar</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('tamplate/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{asset('tamplate/vendor/metisMenu/metisMenu.min.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('tamplate/dist/css/sb-admin-2.css')}}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{{asset('tamplate/vendor/morrisjs/morris.css')}}" rel="stylesheet">

    {{--main css--}}
    <link href="{{asset('css/main.css')}}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{asset('tamplate/vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->




</head>

resources/views/includes/_leftBar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">

                <a href="{{route('mySites')}}"><i class="fa fa-bar-chart-o fa-fw"></i>  Sites<span class="fa arrow"></span></a>


                    <li>
                        <a href="{{route('mySites')}}"> My Sites</a>
                    </li>
                    <li>
                        <a href="{{route('create')}}"> Create Site</a>
                    </li>

            <a href=""><i class="fa fa-bar-chart-o fa-fw"></i>Bars<span class="fa arrow"></span></a>
                    <li>
                        <a href="{{route('bars.index')}}"> Create Bar</a>
                    </li>
                    <li>
                        <a href="{{route('bars.index')}}"> Edit Bars</a>
                    </li>


                <!-- /.nav-second-level -->

        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>

resources/views/includes/_navbar.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{action('HomeController@index')}}">CoolBar</a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links defaultSite">
    <li class="dropdown">
        <select class="form-control default_site_small" id="selectSite" name="bar" style="border: 2px solid gray;margin-top: 6px;">>
            @forelse($sites as $site)
                <option value="{{$site->id}}" aria-checked="true"
                    @if($site->id == Auth::user()->default_site)
                        selected
                    @endif>
                    {{$site->site_host}}
                </option>
            @empty
                <option value="">You Have Not Created Sites Yet</option>
            @endforelse
        </select>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="{{route('create')}}"><i class="fa fa-user fa-fw"></i> Add New Site</a>
            </li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider">Add Site</li>

        </ul>
        <!-- /.dropdown-user -->
    </li>
    <ul class="nav navbar-top-links navbar-right">

        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-alerts">
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small">12 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small">4 minutes ago</span>
                        </div>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-alerts -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i>{{Auth::user()->name}}</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>

                <li>
                    <a href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i>
                        Logout
                    </a>
                </li>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

<!-- /.navbar-static-side -->
</nav>